### ISSUE TITLE
about evaluation result

### ISSUE THREAD

**Issue by amiltonwong** [fregu856/deeplabv3#3]
Hi, @fregu856 ,

Thanks for releasing such a useful package using pytorch. I had practiced on `eval_on_val_for_metrics.py` as [guided](https://github.com/fregu856/deeplabv3#evaluationeval_on_val_for_metricspy), and obtain the same metrics output as yours. I'm concerning about the big gap between your result and the official deeplabv3+ result.
The class IOU of yours is 59.3, while the official deeplabv3+ is reported as 82.1.
Could you list the difference regarding your implementation? Is the provided pre-trained model `model_13_2_2_2_epoch_580.pth` a very preliminary training result?

THX!

**Comment by fregu856** [comment]
Hi,

Good question!

I didn't spend too much time tuning hyperparams etc., the main factor is however that the model is trained on 512x1024 images (instead of the original 1024x2048). To be able to use the cityscapes scripits, I thus simply upsample the model output to 1024x2048, which obviously will have a negative effect on the metrics.
